### ISSUE TITLE
Not reading config file

### ISSUE THREAD

**Issue by csthomas2** [sophos-cybersecurity/sophos-central-api-connector#1]
Upon first run sophos_central_main.py would error with configparser.NoSectionError: No section: 'static' indicating the config file wasn't being read. Updated config\sophos_central_api_config.py paths with a prefixed dot (or removed preceeding slashes).

**Comment by moledaemon** [comment]
Can you specify the version of Python and OS you are using. Also please can you provide the syntax used when you see this error please.

**Comment by csthomas2** [comment]
Windows 10 1910. I was using Python 3.8.2. Then moved to Python 3.7.7 and started with a fresh install with pip. Issue persisted across versions

python sophos_central_main.py -a static

I could specify any number of other arguments but it would always result with the above error until the paths were fixed in the config file.

**Comment by moledaemon** [comment]
This looks like its an issue with the reading of the file path for the config file. As a workaround you will need to add the absolute file path as a raw entry whilst i work on a more permanent fix. e.g change:
splunk_conf_path = PureWindowsPath("\\config\\sophos_config.ini")
to: 
sophos_conf_path = r'<absolute_path_tofile>\sophos_config.ini'

This setting is found in the file: sophos_central_api_config.py under the config folder

**Comment by moledaemon** [comment]
@csthomas2  this is now fixed in 0.1.1. Please obtain this from pypi using:
pip install sophos-central-api-connector==0.1.1
