### ISSUE TITLE
Errored when pulling alerts/inventory

### ISSUE THREAD

**Issue by csthomas2** [sophos-cybersecurity/sophos-central-api-connector#2]
sophos_central_api_connector_utils.py", line 115, in validate_page_size
    elif int(page_size) <= api_conf.max_alerts_page:
ValueError: invalid literal for int() with base 10: ''

Seems like the defaults in sophos_central_api_config.py were not being used. Fixed by entering values in sophos_config.ini

**Comment by moledaemon** [comment]
Can you specify the version of Python and OS you are using. Also please can you provide the syntax used when you see this error please.

**Comment by csthomas2** [comment]
Windows 10 1910. I was using Python 3.8.2. Then moved to Python 3.7.7 and started with a fresh install with pip. 

C:\Users\Chris\AppData\Local\Programs\Python\Python37\Lib\site-packages\sophos_central_api_connector>python sophos_central_main.py -a static -g alerts
Traceback (most recent call last):
  File "sophos_central_main.py", line 400, in <module>
    main(args)
  File "sophos_central_main.py", line 357, in main
    get_alerts(tenant_info, output, poll, days, reset_flag, page_size, splunk_creds, tenant)
  File "sophos_central_main.py", line 74, in get_alerts
    page_size = api_utils.validate_page_size(page_size, api)
  File "C:\Users\Chris\AppData\Local\Programs\Python\Python37\lib\site-packages\sophos_central_api_connector\sophos_central_api_connector_utils.py", line 115, in validate_page_size
    elif int(page_size) <= api_conf.max_alerts_page:
ValueError: invalid literal for int() with base 10: ''

**Comment by moledaemon** [comment]
you need to ensure that you have a value in the sophos_config.ini for the page size e.g.

[page_size]
inventory_ps: 50
alerts_ps: 50

**Comment by moledaemon** [comment]
@csthomas2  this is now fixed in 0.1.1. Please obtain this from pypi using:
pip install sophos-central-api-connector==0.1.1
