### ISSUE TITLE
Pulling alerts results in variable error

### ISSUE THREAD

**Issue by csthomas2** [sophos-cybersecurity/sophos-central-api-connector#3]
No tenant specified. Script will pull some alerts, but eventually errors as below.

ERROR:root:Response Code: 403
ERROR:root:Error Details: b'{\n    "error": "forbidden",\n    "correlationId": "<blanked>",\n    "requestId": "<blanked>",\n    "message": "Access is denied"\n}'
Traceback (most recent call last):
  File "sophos_central_main.py", line 400, in <module>
    main(args)
  File "sophos_central_main.py", line 357, in main
    get_alerts(tenant_info, output, poll, days, reset_flag, page_size, splunk_creds, tenant)
  File "sophos_central_main.py", line 129, in get_alerts
    json_data = get_api.get_data(tenant_url_data, page_size, tenant_id, api)
  File "sophos_central_api_connector\sophos_central_api_get_data.py", line 18, in get_data
    ep_item_data = ep_data['items']
TypeError: 'NoneType' object is not subscriptable

**Comment by moledaemon** [comment]
Can you specify the version of Python and OS you are using. Also please can you provide the syntax used when you see this error please.

**Comment by csthomas2** [comment]
I think this error might be more of an issue with some of my tenants. As I specify tenants, I am able to get alerts normally from some and not others. Will have to investigate more.

**Comment by moledaemon** [comment]
If the issue persists please raise a new issue with the further investigation steps you carried out
