### ISSUE TITLE
KeyError: 'static'

### ISSUE THREAD

**Issue by ceoz** [sophos-cybersecurity/sophos-central-api-connector#4]
Whenever i run that script the KeyError: 'static' message is what i get.
Running on Ubuntu 18 with python 3.6.9

Is the config file nor read?

**Comment by craig-sophos** [comment]
The minimum requirement for this is Python 3.7, can you try with that and if you still have an issue come back to us.

**Comment by ceoz** [comment]
hi, thanks for your reply.
i upgraded python and ran the script again.

python3.7 sophos_central_main.py -a static --get tenants
Traceback (most recent call last):
  File "sophos_central_main.py", line 400, in <module>
    main(args)
  File "sophos_central_main.py", line 314, in main
    client_id, client_secret = get_sophos_creds(sophos_auth, sophos_final_path)
  File "sophos_central_main.py", line 237, in get_sophos_creds
    client_id = sophos_conf.get('static', 'client_id')
  File "/usr/lib/python3.7/configparser.py", line 780, in get
    d = self._unify_values(section, vars)
  File "/usr/lib/python3.7/configparser.py", line 1146, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'static'

the keys are in the config.ini.

any advice?

**Comment by moledaemon** [comment]
This looks like its an issue with the reading of the file path for the config file. As a workaround you will need to add the absolute file path as a raw entry whilst i work on a more permanent fix. e.g change:
splunk_conf_path = PureWindowsPath("\\config\\sophos_config.ini")
to: 
sophos_conf_path = r'<absolute_path_tofile>\sophos_config.ini'

This setting is found in the file: sophos_central_api_config.py under the config folder

**Comment by moledaemon** [comment]
@ceoz this is now fixed in 0.1.1. Please obtain this from pypi using:
pip install sophos-central-api-connector==0.1.1
